---
name: CI

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+.x
  pull_request:
    branches:
      - master
      - v[0-9]+.[0-9]+.x

jobs:
  tests:
    if: ${{ github.repository_owner == 'sopel-irc' }}
    name: Quality & Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel
          python -m pip install --upgrade -r requirements.txt
          python -m pip install -e .
      - name: Lint
        run: make lint
      - name: Tests
        run: make test
